// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBatn_mKDMswhr6AoZwJkBu-VRVr5OezEY',
    appId: '1:637102657592:android:8b072976405ba364d696cd',
    messagingSenderId: '637102657592',
    projectId: 'almost-expired-food-887dd',
    storageBucket: 'almost-expired-food-887dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfyQ4Kl605FD8qfj37rJryaAn0itACifg',
    appId: '1:637102657592:ios:895ad3e2c785b8e9d696cd',
    messagingSenderId: '637102657592',
    projectId: 'almost-expired-food-887dd',
    storageBucket: 'almost-expired-food-887dd.appspot.com',
    androidClientId: '637102657592-7ra3p7stn1v2ikte41nin9vmebus3n4m.apps.googleusercontent.com',
    iosClientId: '637102657592-an3njvcbp8s6o6i0d9ophlkf61b82pqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.appetit',
  );
}
